#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_flask:latest', 'gcr.io/$PROJECT_ID/workspace_flask']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_react:latest', 'gcr.io/$PROJECT_ID/workspace_react']
images: ['gcr.io/$PROJECT_ID/workspace_flask', 'gcr.io/$PROJECT_ID/workspace_react']
