version: '3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
     - 3003:3003
    environment:
     PORT: 3003
     FLASK_ENV: 'test'
     SOMETHING: 'right_here'
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    restart: always
    ports:
     - 3002:3002
    environment:
     PORT: 3002
