version: '3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
     - 3002:3002
    environment:
     PORT: 3002
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    restart: always
    ports:
     - 3001:3001
    environment:
     PORT: 3001
