# this docker-compose.yaml is non-functional at the moment...
# test without docker and then only deploy to Cloud RUn? so don't use this
# Cloud Build should be a faster build time anyways than docker-compose.yaml
---
version: '3'
services:
  flask:
    env_file: ./.env
    image: python:2.7-slim
    volumes:
      - ./gateway:/usr/src
    command:
      /usr/src/run.sh
    ports:
      - "9005:9005"
    links:
      - countries
      - rng
    depends_on:
      - other1
      - other2
