version: '3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
     - "${PORT:-8080}"
    environment:
     # /run/docs/reference/container-contract
     PORT: ${PORT:-8080}
    #  K_SERVICE: sample-app
